version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 5
    reviewers:
      - "ahmad-alwakai"
    assignees:
      - "ahmad-alwakai"
    labels:
      - "dependencies"
      - "needs-review"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: "@prisma/client"
        update-types: ["version-update:semver-major"]
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 3
    reviewers:
      - "ahmad-alwakai"
    assignees:
      - "ahmad-alwakai"
    labels:
      - "dependencies"
      - "github-actions"
      - "needs-review"

  # Enable version updates for Docker (if applicable)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 3
    reviewers:
      - "ahmad-alwakai"
    assignees:
      - "ahmad-alwakai"
    labels:
      - "dependencies"
      - "docker"
      - "needs-review"
