# GitHub Labels Configuration
# This file defines the labels used in the Speedy Van repository

labels:
  # Priority Labels
  - name: "priority: high"
    color: "d73a4a"
    description: "High priority issue or feature"
  - name: "priority: medium"
    color: "fbca04"
    description: "Medium priority issue or feature"
  - name: "priority: low"
    color: "0e8a16"
    description: "Low priority issue or feature"

  # Type Labels
  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"
  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"
  - name: "documentation"
    color: "0075ca"
    description: "Improvements or additions to documentation"
  - name: "good first issue"
    color: "7057ff"
    description: "Good for newcomers"
  - name: "help wanted"
    color: "008672"
    description: "Extra attention is needed"

  # Status Labels
  - name: "needs-review"
    color: "ff6a00"
    description: "Needs review from maintainers"
  - name: "blocked"
    color: "d93f0b"
    description: "Blocked by other issues or dependencies"
  - name: "in-progress"
    color: "1d76db"
    description: "Work in progress"
  - name: "ready-for-review"
    color: "0e8a16"
    description: "Ready for code review"

  # Component Labels
  - name: "frontend"
    color: "0052cc"
    description: "Frontend/UI related changes"
  - name: "backend"
    color: "5319e7"
    description: "Backend/API related changes"
  - name: "database"
    color: "fbca04"
    description: "Database schema or query changes"
  - name: "mobile"
    color: "c2e0c6"
    description: "Mobile-specific changes"
  - name: "security"
    color: "d93f0b"
    description: "Security-related changes"

  # Process Labels
  - name: "agent"
    color: "00e0ff"
    description: "Agent-authored changes"
  - name: "ci"
    color: "1d76db"
    description: "CI/CD pipeline changes"
  - name: "dependencies"
    color: "0366d6"
    description: "Pull requests that update a dependency file"
  - name: "github-actions"
    color: "000000"
    description: "GitHub Actions related changes"
  - name: "docker"
    color: "2496ed"
    description: "Docker related changes"

  # Special Labels
  - name: "breaking-change"
    color: "d93f0b"
    description: "Breaking change that requires migration"
  - name: "performance"
    color: "ff6a00"
    description: "Performance improvements"
  - name: "accessibility"
    color: "1d76db"
    description: "Accessibility improvements"
  - name: "testing"
    color: "0e8a16"
    description: "Testing related changes"
