name: Brand Assets Check
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  brand-assets:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Debug repository state
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Looking for pnpm-lock.yaml:"
          ls -la pnpm-lock.yaml || echo "pnpm-lock.yaml not found"

      - name: Install dependencies (with fallback)
        run: |
          if [ -f pnpm-lock.yaml ]; then
            echo "Lockfile found, installing with frozen flag for deterministic builds"
            pnpm install --frozen-lockfile --prefer-offline
          else
            echo "No lockfile found, generating one and installing dependencies"
            pnpm install --prefer-offline
          fi

      # Cache PNPM store explicitly if needed by separate cache action (optional)
      # - name: Cache pnpm store
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.pnpm-store
      #     key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pnpm-

      - name: Optimize SVGs (svgo)
        run: |
          # Adjust the directory if your assets folder differs
          ASSETS_DIR="apps/web/public"
          # Optimize any SVGs found under public (logos, icons, etc.)
          pnpm svgo -f "$ASSETS_DIR" || true

      - name: Commit optimized brand assets
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Stage only changed SVG files anywhere under public
          CHANGES=$(git ls-files -m | grep -E '^apps/web/public/.*\.svg$' || true)
          if [ -n "$CHANGES" ]; then
            git add $CHANGES
            git commit -m "🔧 Optimize brand assets with SVGO"
            git push
          else
            echo "No SVG changes to commit."
          fi
